In [137]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [138]:
df = pd.read_csv(r"D:\ML\Intro to ML Course\Week5\Assignment\tips.csv")

In [139]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [183]:
df["sex"] = df["sex"].replace({"Male":0, "Female":1})
df["smoker"] = df["smoker"].replace({"No":0, "Yes":1})
df["day"] = df["day"].replace({"Sun":0, "Mon":1, "Tue":2, "Wed":3, "Thur":4, "Fri":5, "Sat":6})
df["time"] = df["time"].replace({"Lunch":0, "Dinner":1})

In [199]:
#df["tip_perc"] = ((df["tip"] / df["total_bill"]) * 100).round(0)
df["tip_perc"] = np.ceil((df["tip"] / df["total_bill"]) * 100 / 5) * 5

def classify_tip_perc(value):
    if value > 30:
        return 30
    else:
        return value

df['tip_class'] = df['tip_perc'].apply(classify_tip_perc)

df.tail()

total_bill   tip  sex  smoker  day  time  size  tip_perc  tip_class
239       29.03  5.92    0       0    6     1     3      25.0       25.0
240       27.18  2.00    1       1    6     1     2      10.0       10.0
241       22.67  2.00    0       1    6     1     2      10.0       10.0
242       17.82  1.75    0       0    6     1     2      10.0       10.0
243       18.78  3.00    1       0    4     1     2      20.0       20.0

In [200]:
X = df.drop("tip_class", axis=1)
y = df["tip_class"]

In [201]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [202]:
from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train, y_train)

DecisionTreeClassifier()

In [203]:
tree_pred = decision_tree.predict(X_test)

In [204]:
from sklearn.metrics import classification_report, confusion_matrix

In [205]:
print(confusion_matrix(y_test, tree_pred))
print("---")
print(classification_report(y_test, tree_pred))

[[ 4  0  0  0  0]
 [ 0 17  0  0  0]
 [ 0  0 20  0  0]
 [ 0  0  0  6  0]
 [ 0  0  0  0  2]]
---
              precision    recall  f1-score   support

        10.0       1.00      1.00      1.00         4
        15.0       1.00      1.00      1.00        17
        20.0       1.00      1.00      1.00        20
        25.0       1.00      1.00      1.00         6
        30.0       1.00      1.00      1.00         2

    accuracy                           1.00        49
   macro avg       1.00      1.00      1.00        49
weighted avg       1.00      1.00      1.00        49



## Random Forest

In [206]:
from sklearn.ensemble import RandomForestClassifier

In [207]:
random_forest_model = RandomForestClassifier()

random_forest_model.fit(X_train, y_train)
random_pred = random_forest_model.predict(X_test)

In [208]:
print(confusion_matrix(y_test, random_pred))
print("---")
print(classification_report(y_test, random_pred))

[[ 4  0  0  0  0]
 [ 0 17  0  0  0]
 [ 0  0 20  0  0]
 [ 0  0  3  3  0]
 [ 0  0  1  0  1]]
---
              precision    recall  f1-score   support

        10.0       1.00      1.00      1.00         4
        15.0       1.00      1.00      1.00        17
        20.0       0.83      1.00      0.91        20
        25.0       1.00      0.50      0.67         6
        30.0       1.00      0.50      0.67         2

    accuracy                           0.92        49
   macro avg       0.97      0.80      0.85        49
weighted avg       0.93      0.92      0.91        49

